version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: project_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: ratings_dev_db
      MYSQL_USER: projectuser
      MYSQL_PASSWORD: abc123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./application/server/scripts/DB.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data:
