name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      TEST_HOST: localhost
      TEST_USER: root
      TEST_PASSWORD: root
      TEST_DATABASE: ratings_test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your project's Node.js version

      - name: Install dependencies
        working-directory: ./application/server
        run: npm install --force

      - name: Set environment variables
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Run tests
        working-directory: ./application/server
        run: npm test