name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your project's Node.js version

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Configure MySQL root access
        run: |
          echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';" > init.sql
          sudo mysqld --init-file=init.sql &
          sleep 10

      - name: Create test database
        run: mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS ratings_test_db;"

      - name: Set up environment variables for testing
        working-directory: ./application/server
        run: |
          echo "NODE_ENV=test" > .env.test
          echo "HOST=127.0.0.1" >> .env.test
          echo "USER_STRING=root" >> .env.test
          echo "PASSWORD=root" >> .env.test
          echo "DATABASE=ratings_test_db" >> .env.test
          echo "PORT=3306" >> .env.test
          echo "JWT_SECRET=abc123" >> .env.test
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.test
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.test
          echo "RAWG_API_KEY=${{ secrets.RAWG_API_KEY }}" >> .env.test
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.test
          cat .env.test

      - name: Debug Secrets
        run: |
          echo "Checking secrets"
          echo "GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}"
          echo "GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}"
          echo "RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}"
          echo "OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}"

      - name: Debug Loaded Environment Variables
        run: |
          echo "Loaded environment variables:"
          cat .env.test
          grep 'GOOGLE_CLIENT' .env.test || echo "GOOGLE_CLIENT not found"

      - name: Install dependencies
        working-directory: ./application/server
        run: npm install --force

      - name: Run tests
        working-directory: ./application/server
        env:
          NODE_ENV: test
        run: npm test